### ISSUE TITLE
The username is already being used

### ISSUE THREAD

**Issue by Leny1996** [owncloud-docker/server#101]
Hi, the issue mentioned in #68 still exists.
Everything works great until stopping containers.
Steps to reproduce:
docker-compose up -d
docker-compose restart

Now it cannot start and the only solution is creating a fresh one.

**Comment by tboerger** [comment]
This happens only if you remove the generated config . php, than it tries to install owncloud again, but the database is already populated.

Please keep the volume for files and configs and it works fine.

**Comment by Leny1996** [comment]
Yes, but why config.php is deleted when running docker-compose restart?

**Comment by tboerger** [comment]
I don't know what exactly gets done on your side, the docker image is not deleting any configuration. Just docker-compose got some option to drop named volumes.

Exactly the same docker-compose configuration is running on various places and operating systems without any issue on restarting the stack.

**Comment by Leny1996** [comment]
I've investigated docker containers - redis and mariaDB starts without problems. Only owncloud container is still restarting because of "The username is already being used". Restarting redis and mariaDB doesn't break anything - only restarting owncloud container breaks configuration and I cannot enter bash while container is still restarting.

**Comment by tboerger** [comment]
There is not really a known path to get back to the system beside starting the db from scratch

**Comment by MRwangyd** [comment]
@Leny1996 Have you solved your problem

**Comment by MRwangyd** [comment]
I also encountered this problem in the https://github.com/owncloud-docker/server/issues/104

**Comment by MRwangyd** [comment]
This problem occurs when rebuilding the owncloud to start

**Comment by MRwangyd** [comment]
I use Launch with plain docker Way to start

**Comment by skavadias** [comment]
I believe the problem is that in `mariadb`, in database `owncloud` in table `oc_users` (where 'oc_' is the tableprefix) the user 'admin' already exists. So, running --somehow (e.g., with `docker exec container_name`)-- on `mariadb` the command
`DELETE FROM owncloud.oc_users WHERE uid='admin';`
will fix it, the next time. But, I guess, you'll have to stop the restarting container for service owncloud first, so it does not issue commands to `mariadb` at the same time.

_I haven't verified this with docker and owncloud_, because I I encountered the problem with nextcloud re-installation.

I hope this helps anyone still having this problem.
