### ISSUE TITLE
[QA]  Apache reload fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud-docker/server#225]
Seen in both owncloud/server:10.6 and owncloud/server:10.7

```
root@15d8c0afd5ed: /var/www/owncloud # service apache2 reload
 /etc/init.d/apache2: 46: .: Can't open /etc/apache2/envvars
 /etc/init.d/apache2: 57: .: Can't open /etc/apache2/envvars
 ERROR: APACHE_PID_FILE needs to be defined in /etc/apache2/envvars
```

Workaround: `kill -HUP $(cat /var/run/apache2/apache2.pid)`

**Comment by xoxys** [comment]
Of course this will not work as Apache is started as a foreground process and not as a service. Keep in mind its a docker container not a VM :) 

Another option would be to use `source /etc/entrypoint.d/99-apache.sh && apachectl -k graceful`. If one of these options already works for you I'm going to close the issue. Otherwise, we could add a small helper script to reload Apache if that would help you in the QA workflow.

**Comment by wkloucek** [comment]
> Of course this will not work as Apache is started as a foreground process and not as a service. Keep in mind its a docker container not a VM :)

I agree, just restart the container.
