### ISSUE TITLE
Server restarting and db unhealthy

### ISSUE THREAD

**Issue by itsCasper** [owncloud-docker/server#53]
Had success in starting owncloud using the docker-compose command.  But after stopping it to make edits to the yml and env files for ports, it is now not starting, but rather restarting constantly.
The ps command shows that the db is unhealthy and the server itself restarting.
Running latest docker, owncloud CE server on a Mac Mini 2012 under macOS 10.13.

Will remove the ownlcoud and reinstall if that is the best advice as I am not sure where to look for what is causing this.

Images show the output from ps and from the run command without the -d.

Any help would be much appreciated.

<img width="678" alt="screenshot 2018-05-01 14 35 20" src="https://user-images.githubusercontent.com/38891795/39487509-75a21b8e-4d4d-11e8-8524-baaf900af6a9.png">
<img width="495" alt="screenshot 2018-05-01 14 35 48" src="https://user-images.githubusercontent.com/38891795/39487510-75aecfbe-4d4d-11e8-851f-441225ad1c59.png">

**Comment by danieldeusing** [comment]
same as #52

**Comment by tboerger** [comment]
I'm on it, I will update this issue when a fix have been published

**Comment by alejandrofcarrera** [comment]
Same from my side. My company is using this software and after a pull of the latest Docker image, the owncloud is not launched correctly anymore. For us, it is critical because we do not have access to all the files of the company (although we have a complete backup of the vps)

Firstly the same message of above:
> ownCloud is already latest version

After remove the latest version, i tried with 10.0.7 tag but this message appears:
> The username is already being used

Any guide to revert to the old version? Maybe it is not necessary to upgrade if there is not huge changes.

**Comment by tboerger** [comment]
Please upgrade the docker image with `docker-compose pull`, the issue have been resolved.
