### ISSUE TITLE
custom page

### ISSUE THREAD

**Issue by qinzheng** [owncloud-docker/server#60]
I want to custom htmls and css   so  which folder should I mount as volumes

**Comment by tboerger** [comment]
The owncloud root folder is located at `/var/www/owncloud`, so you can mount files or folders where ever you need and want to do.

**Comment by qinzheng** [comment]
`volumes:
      - /home/mc2/owncloud-docker-server/volumes/web/data:/mnt/data
      - /home/mc2/owncloud-docker-server/volumes/web/core:/var/www/owncloud/core`

This is my docker-compose.yml    but it can't start   errors like this:
`PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/lib/private/Console/../../../core/register_command.php' (include_path='/var/www/owncloud/apps:/var/www/owncloud/custom') in /var/www/owncloud/lib/private/Console/Application.php on line 91`

**Comment by tboerger** [comment]
That would tell me that your `core` volume doesn't include all core files. Volumes are mounted and not synced, so if you want to overwrite the core folder you have to provide the entire folder. Maybe you want to use `owncloud/base` instead of `owncloud/server` where you can mount the entire owncloud tarball at `/var/www/owncloud` so that you can manipulate every part of the ownCloud.
