### ISSUE TITLE
Add custom SSL chain certificate

### ISSUE THREAD

**Issue by lukas-koschmieder** [owncloud-docker/server#89]
Hi, 

1. Could you include an option to add custom Apache SSL chain certificates? All you would have to do is adding a single line such as `SSLCertificateChainFile /mnt/data/certs/ssl-chain.crt ` to `/etc/apache2/sites-enabled/000-default.conf`.
2. Could you tell me where the corresponding section `<IfModule mod_ssl.c>...</IfModule>` in `/etc/apache2/sites-enabled/000-default.conf` is generated? The closest thing that I could find in your GitHub project is this template here: https://github.com/owncloud-docker/base/blob/master/rootfs/etc/templates/apache.conf. But it only generates the ``VirtualHost`` section.

Cheers,
Lukas

**Comment by tboerger** [comment]
The SSL functionality have been dropped recently. The container is listening to 8080 only now.

If you want to customize the image to get back ssl termination you can overwrite https://github.com/owncloud-docker/base/blob/master/rootfs/etc/templates/apache.conf and https://github.com/owncloud-docker/php/blob/master/rootfs/etc/apache2/ports.con. 

But anyway we suggest to use a reverse proxy like nginx, haproxy or traefik for SSL termination.

**Comment by lukas-koschmieder** [comment]
Could you briefly explain why you would use a reverse proxy in addition to an Apache server that is already there and perfectly capable of doing the same job?

**Comment by tboerger** [comment]
Because the majority of people anyway got running more than one web service on a single server and because the handling of SSL offloading, usage of let's encrypt certificates and so on is properly in the control of the administrator and is not tied to containers build by third parties like ownCloud.

**Comment by yebo29** [comment]
This one change completely and utterly broke my installation. I was using normal ports 80 and 443 and everything was working fine until I erroneously decided to upgrade from 10.0.9. A deprecation warning would have been nice instead of a cold hard cutover. I've spent hours troubleshooting this and now can't login with error "You took to long to login". I've disabled apps, cleared cookies and cache, tried different browsers, PHP up to date, restarted both containers and host, added doamin to trusted domains list, and more. 
I am abandoning this project. It's been a headache since day 1.

**Comment by tboerger** [comment]
We have discussed this breaking change a lot internally, it wasn't a quick decision. 

But anyway you should read changelogs before upgrades, there it had been clearly written that the port have been changed.

There had been multiple reasons for this change, but since you decided to abond this project I don't need to write down everything.

Headache from the beginning? Funnily we never received any complaint from you.

**Comment by yebo29** [comment]
You are right, no doubt about that. I should have definitely read the release notes.
 I didn't complain because most things I've been able to solve on my own, but this one was one that absolutely stumped me, and continues to do so, but it's okay, lesson learned. I apologize for my outbreak. It's just been 3/4 a day blown on this so understandably I'm quite frustrated. 

You live you learn. I apologize.

**Comment by yebo29** [comment]
And this gives me the opportunity to play with a reverse proxy, so all is good.
