### ISSUE TITLE
.env-File Mapping to Images

### ISSUE THREAD

**Issue by thaxy** [owncloud-docker/server#98]
Hello,

In my eyes, the ``.env`` files is completely useless right now since it's not being passed to the images.
Configuration changes as mentioned [here](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/#installation-on-a-local-machine) don't take any effect because of that.
The following directive may do the trick:

```
env_file:
    - web-variables.env
```

[``docker-compose.yml``](https://github.com/owncloud-docker/server/blob/master/docker-compose.yml)

**Comment by tboerger** [comment]
It's definitely not totally useless, docker-compose automatically sources `.env` files, so the environment variables defined within this file are available for interpolation within the docker-compose.yml. We are using that for the image version and some other variables like the host port mapping.

The configuration changes mentioned at https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/#installation-on-a-local-machine are already used automatically be docker-compose at https://github.com/owncloud-docker/server/blob/master/docker-compose.yml#L15, https://github.com/owncloud-docker/server/blob/master/docker-compose.yml#L23 and https://github.com/owncloud-docker/server/blob/master/docker-compose.yml#L29-L30. So, instead of telling others that their efforts are totally useless you should try it carefully first.

Beside that, this docker-compose configuration is just a reference how you can easily get started. It's not our goal to show all possible options or to make everything instantly configurable. If we want to do that we would result in ~20 different docker-compose.yml snippets.

**Comment by thaxy** [comment]
You are right I tried to add other env variables such as [``APACHE_LISTEN``](https://github.com/owncloud-docker/php/blob/master/rootfs/etc/entrypoint.d/99-apache.sh#L75) to the ``.env`` file and wondered why they didn't change within the container. I came from another project where this was the case and didn't see the ``${}`` syntax. Don't take it personal, that's why I wrote 

> In my eyes, [...]

Thanks for your help and the effort.
